services:
  auth:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api-auth
    ports:
      - '8081:8081'
    environment:
      USER_SERVICE_URL: http://api-usuario:8082
    networks:
      - compose_kong-net

networks:
  compose_kong-net:
    external: true
