networks:
  kong-net:
    external: true

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: mercadox-prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - kong-net
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: mercadox-grafana
    ports:
      - "3000:3000"
    networks:
      - kong-net
