services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-produto
    environment:
      POSTGRES_DB: produtos
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kong-net

 # app:
  #  build:
   #   context: .
    #  dockerfile: ./Dockerfile
    #container_name: api-produtos
   # ports:
   #   - '8083:8083'
   # depends_on:
   #   - postgres
   # environment:
   #   SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/produtos
   #   SPRING_DATASOURCE_USERNAME: root
   #   SPRING_DATASOURCE_PASSWORD: root
   #   AWS_REGION: us-east-1
   #   AWS_ACCESS_KEY_ID: test
   #   AWS_SECRET_ACCESS_KEY: test
   #   SQS_ENDPOINT: http://localstack:4566
   #   S3_ENDPOINT: http://localstack:4566
   # networks:
   #  - mercadox_network

volumes:
  postgres_data:

networks:
  kong-net:
    external: true
