
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-usuario
    environment:
      POSTGRES_DB: usuarios
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - compose_kong-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-usuario
    ports:
      - '8082:8082'
    depends_on:
      - postgres
      - localstack  # Adicione isso para garantir que o LocalStack esteja em execução antes do app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/usuarios
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      SQS_ENDPOINT: http://localstack:4566
    networks:
      - compose_kong-net

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4566:4566'  # Porta para os serviços da AWS simulados
      - '4510-4560:4510-4560'  # Portas para certificados e outras ferramentas
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    networks:
      - compose_kong-net

volumes:
  postgres_data:

networks:
  compose_kong-net:
    external: true
