services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: usuarios
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/usuarios
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      SQS_ENDPOINT: http://localstack-main:4566
      S3_ENDPOINT: http://localstack-main:4566
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge